apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-app
  namespace: {{ default "test-app" .Release.Namespace }}
  labels:
    app: test-app
spec:
  hosts:
  - "*"
  gateways:
  - test/test-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: test.app.svc.cluster.local
        port:
          number: 8201
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-gateway
spec:
  selector:
          istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 8201
      name: "8201"
      protocol: HTTP
    hosts:
    - "*"
