# This is the image used to start each pod.
image: cubicnextcloudregistry.azurecr.io/cts/ccbo/test_app:latest

# These are the args used when starting the container in each pod.
#args: ["testing"]

# This is the spec.replicas value for the deploymet.
replicas: "1"

# These are the env vars that are set in each pod.
env:
  # Nonsensitive env vars
  configmap:
    JDBC_URL: jdbc:oracle:thin:@test-dbhost.azure.com:1521/test_app
    JDBC_USER: test_app
    JDBC_PASSWORD: test_app
    JDBC_DRIVER: oracle.jdbc.OracleDriver
    JDBC_SCHEMA: TEST_MAIN
    JDBC_DIALECT: org.hibernate.dialect.Oracle10gDialect
